version: "3"

services:
  api:
    build: .
    container_name: express_test
    depends_on:
      - mysql
      - redis
    ports:
      - 80
    networks:
      - backend
    environment:
      - MYSQL_HOST=mysql_test
      - MYSQL_USER=admin
      - MYSQL_PASS=secret
      - MYSQL_DB=my_db
      - REDIS_SERVER=redis
    volumes:
      - ./:/usr/src/app
      - static_test_files:/usr/src/app/docs
      - /usr/src/app/node_modules/
    command: "npm run dev"

  mysql:
    image: mysql:8.0
    container_name: mysql_test
    networks:
      - backend
    volumes:
      - mysql_test_vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    ports:
      - 3310:3306

  redis:
    image: "redis"
    container_name: redis_test
    networks:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx_test
    ports:
      - 5001:80
    depends_on:
      - api
    networks:
      - backend

networks:
  backend:

volumes:
  api_test_vol:
  mysql_test_vol:
  static_test_files:
